import { onReady } from './utils/dom.js';
import { injectGlobalStyles } from './features/global-styles.js';
import { normalizeArticleLayout } from './features/article-layout.js';
import { initActiveNavigation } from './features/navigation.js';
import { applyPortfolioUpgrades } from './features/portfolio-upgrades.js';
import { initContactForm } from './features/contact-form.js';
import { polishContent } from './features/content-polish.js';
import { initFilters } from './features/filters.js';
import { initGridCanvas } from './features/grid-canvas.js';
import { initMobileMenu } from './features/mobile-menu.js';
import { initMotionEnhancements } from './features/motion.js';
import { initPageTransitions } from './features/page-transitions.js';
import { initResumeDownload } from './features/resume.js';
import { initShareButtons } from './features/share.js';
import { ensureSiteFooter } from './features/site-footer.js';
import { initTheme } from './features/theme.js';

onReady(() => {
  injectGlobalStyles();
  normalizeArticleLayout();
  polishContent();
  applyPortfolioUpgrades();
  initTheme();
  initMobileMenu();
  initGridCanvas();
  initActiveNavigation();
  initFilters();
  initMotionEnhancements();
  initPageTransitions();
  initResumeDownload();
  initShareButtons();
  initContactForm();
  ensureSiteFooter();
});
