const {replaceMain}=require('./shared.cjs');
const rows=[['01','Product design and UX/UI','Clarify journeys, hierarchy, states and interaction rules, then turn them into polished responsive interfaces.','User flows / high-fidelity UI / prototypes','/product-design-nepal'],['02','SaaS dashboards and workflows','Structure tables, filters, roles, forms, permissions and operational states so complex work remains readable.','Dashboard UX / admin workflows / role-based views','/saas-ux-designer'],['03','Web3 and fintech UX','Make wallet, verification and transaction flows clearer before users approve sensitive or irreversible actions.','Signing context / transaction review / trust states','/web3-ux-designer'],['04','Design systems and handoff','Create shared tokens, components, variants and responsive rules that design and engineering can use consistently.','Figma systems / component states / build notes','/figma-design-systems'],['05','Website UX and redesign','Improve positioning, page architecture, proof and conversion paths for software products and service businesses.','Information architecture / responsive UI / conversion paths','/website-ux-design'],['06','UX audit and remediation','Find usability, accessibility, responsive and implementation issues, then turn them into prioritized fixes.','Severity / evidence / practical fix guidance','/ux-audit']];
const serviceRows=rows.map(([n,title,copy,meta,href])=>`<article class="nrs-editorial-row nrs-service-row"><span class="nrs-row-index">${n}</span><div><h3>${title}</h3><p>${copy}</p><p class="nrs-row-meta">${meta}</p></div><a class="nrs-text-link" href="${href}">View service <span aria-hidden="true">↗</span></a></article>`).join('');
const markup=`<main id="main-content" class="container nrs-spacious-page nrs-services-spacious">
<section class="nrs-page-hero reveal-on-scroll" aria-labelledby="services-title"><div class="nrs-page-hero__title"><p class="eyebrow">Services</p><h1 id="services-title" class="hero-title">Design support for products that need clarity, structure and a cleaner path to build.</h1><p class="body-large">I help software teams turn incomplete requirements, dense workflows and inconsistent interfaces into understandable product experiences and reusable design decisions.</p><div class="nrs-actions"><a class="btn btn-primary" href="/contact">Discuss your product</a><a class="btn btn-secondary" href="/projects">See selected work</a></div></div><aside class="nrs-page-hero__aside"><p class="nrs-aside-intro">Best suited to products complex enough to need design judgment, but practical enough to ship.</p><dl class="nrs-facts"><div><dt>Typical work</dt><dd>SaaS, Web3, fintech, mobile products and product websites</dd></div><div><dt>Engagements</dt><dd>Product roles, focused projects, systems and UX audits</dd></div><div><dt>Delivery</dt><dd>Flows, responsive UI, prototypes, documentation and QA</dd></div></dl></aside></section>
<section class="nrs-section reveal-on-scroll" aria-labelledby="services-list"><header class="nrs-section-heading"><p class="eyebrow">Ways I can help</p><h2 id="services-list" class="section-title">Choose the product problem, not a package name.</h2></header><div class="nrs-editorial-list nrs-service-list">${serviceRows}</div></section>
<section class="nrs-section reveal-on-scroll" aria-labelledby="services-process"><header class="nrs-section-heading"><p class="eyebrow">Process</p><h2 id="services-process" class="section-title">Four stages. Each one removes a different kind of uncertainty.</h2></header><ol class="nrs-editorial-list"><li class="nrs-editorial-row"><span class="nrs-row-index">01</span><h3>Context</h3><p>Users, business goals, constraints, evidence and the current friction.</p></li><li class="nrs-editorial-row"><span class="nrs-row-index">02</span><h3>Structure</h3><p>Journeys, hierarchy, content priority, system states and decision points.</p></li><li class="nrs-editorial-row"><span class="nrs-row-index">03</span><h3>Interface</h3><p>Reusable patterns, responsive screens and reviewable prototypes.</p></li><li class="nrs-editorial-row"><span class="nrs-row-index">04</span><h3>Handoff</h3><p>Behavior notes, edge cases, responsive rules, assets and design QA.</p></li></ol></section>
<section class="nrs-section nrs-section--closing reveal-on-scroll"><div><p class="eyebrow">Start with context</p><h2 class="section-title">Send the product, the friction and the timeline.</h2></div><div class="nrs-closing-copy"><p>I will help define the right design scope after understanding what users and the team are trying to accomplish.</p><div class="nrs-actions"><a class="btn btn-primary" href="/contact">Start a conversation</a><a class="btn btn-secondary" href="/projects">Review the work</a></div></div></section></main>`;
replaceMain('services.html',markup,'nrs-services-spacious-page');
